name: Construir y push

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.EDSON_DOCKERHUB_ID }}
          password: ${{ secrets.EDSON_DOCKERHUB_TOKEN }}


      - name: Configurar QEMU
        uses: docker/setup-qemu-action@v1

      - name: Configurar buildx
        uses: docker/setup-buildx-action@v1

      - name: Construir con buildx
        run: |
          docker buildx build \
          --push \
          --tag amigosinformaticos/configuration_server:latest \
          --platform linux/386,linux/amd64,linux/arm/v6,linux/arm64 .